version: "{branch}-{build}"

image: Visual Studio 2015

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: "true"
  build_dir: C:\msys64\home\appveyor
  build_root: exaile/tools/installer/_build_root
  sdk_name: exaile-sdk-win
  sdk_ver: 6
  sdk_url: https://github.com/exaile/$(sdk_name)/releases/download/$(sdk_name)-$(sdk_ver)/$(sdk_name)-$(sdk_ver).tar.xz
  dist_name: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_REPO_TAG_NAME)

clone_folder: $(build_dir)\$(APPVEYOR_PROJECT_NAME)

clone_depth: 1

cache:
  - C:\msys64\var\cache\pacman\pkg
  - '%build_dir%\%sdk_name%-%sdk_ver%.tar.xz'

init:
  - cmd: |
      REM Update PATH for Bash
      set PATH=C:\msys64\usr\bin;%PATH%
      set GTK_SDK_VERBOSE=1

      REM Show detailed package statistics on pacman -S
      echo [options]>> C:\msys64\etc\pacman.conf
      echo VerbosePkgLists>> C:\msys64\etc\pacman.conf

install:
  - cmd: |
      cd %build_dir%
      git clone --depth=1 https://github.com/exaile/python-gtk3-gst-sdk.git
      bash -lc "[[ -f $sdk_name-$sdk_ver.tar.xz ]] || time wget -O $sdk_name-$sdk_ver.tar.xz $sdk_url"
      bash -lc "time pacman --noconfirm --noprogressbar -Syuu"

before_build:
  - cmd: |
      bash -lc "mkdir $build_root"
      bash -lc "time tar -xf $sdk_name-$sdk_ver.tar.xz -C $build_root"

build_script:
  - cmd: |
      bash -lc "cd exaile/tools/installer && time MAKEFLAGS=-j$(nproc) ../../../python-gtk3-gst-sdk/win_installer/build_win32_installer.sh"

after_build:
  - cmd: |
      move "exaile\tools\installer\exaile-LATEST.exe" "%APPVEYOR_BUILD_FOLDER%\%dist_name%.exe"

artifacts:
  - path: $(dist_name).exe
    name: dist

deploy:
  provider: GitHub
  release: $(dist_name)
  description: ""
  tag: $(APPVEYOR_REPO_TAG_NAME)
  draft: true
  auth_token:
    secure: CMwgWJtvz38DosX01//z6aWr1EVq5y3akaMLZ7pQ+U1eGr1TS91BpdQVwf/4kt0U
  artifact: dist
  on:
    branch: appveyor2
    APPVEYOR_REPO_TAG: true
